{
    "bugid": "1179679",
    "cveid": [
        "CVE-2015-0221"
    ],
    "summary": "CVE-2015-0221 Django: denial of service attack against django.views.static.serve",
    "alias": "CVE-2015-0221",
    "product": "Security Response",
    "hardware": "All",
    "os": "Linux",
    "url": "",
    "reported_date": "2015-01-07 10:26 UTC byMartin Prpi\u010d",
    "attachment": [
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=977194",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=977196",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=977197",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=977198"
    ],
    "comment": [
        "The Django project reports the following issue:\n\n\"\"\"\nIn older versions of Django, the ``django.views.static.serve()`` view read the files it served one line at a time. Therefore, a big file with no newlines would result in memory usage equal to the size of that file. An attacker could exploit this and launch a denial-of-service attack by simultaneously requesting many large files. This view now reads the file in chunks to prevent large memory usage.\n\nNote, however, that this view has always carried a warning that it is not hardened for production use and should be used only as a development aid. Now may be a good time to audit your project and serve your files in production using a real front-end web server if you are not doing so.\n\"\"\"\n\nThis issue is resolved in the upstream versions 1.7.3, 1.6.10, and 1.4.18. Note that Django 1.5 is no longer receiving security updates.\n\nAcknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue.",
        "Createdattachment 977194[details]serve-1.4.x.patch",
        "Createdattachment 977196[details]serve-1.6.x.patch",
        "Createdattachment 977197[details]serve-1.7.x.patch",
        "Createdattachment 977198[details]serve-master.patch",
        "Created Django14 tracking bugs for this issue:\n\nAffects: epel-6 [bug 1181949]",
        "Created python-django14 tracking bugs for this issue:\n\nAffects: fedora-20 [bug 1181947]",
        "Created python-django tracking bugs for this issue:\n\nAffects: fedora-all [bug 1181946]\nAffects: epel-7 [bug 1181948]",
        "External References:https://www.djangoproject.com/weblog/2015/jan/13/security/",
        "python-django-1.6.10-1.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report.",
        "python-django14-1.4.18-1.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report.",
        "python-django-1.6.10-1.fc20 has been pushed to the Fedora 20 stable repository.  If problems still persist, please make note of it in this bug report.",
        "Django14-1.4.18-1.el6 has been pushed to the Fedora EPEL 6 stable repository.  If problems still persist, please make note of it in this bug report.",
        "python-django-1.6.10-1.el7 has been pushed to the Fedora EPEL 7 stable repository.  If problems still persist, please make note of it in this bug report.",
        "all related bzs have been closed already."
    ]
}