{
    "bugid": "1240526",
    "cveid": [
        "CVE-2015-5145"
    ],
    "summary": "CVE-2015-5145 Django: DoS via incorrect URL validation",
    "alias": "CVE-2015-5145",
    "product": "Security Response",
    "hardware": "All",
    "os": "Linux",
    "url": "",
    "reported_date": "2015-07-07 07:49 UTC byMartin Prpi\u010d",
    "attachment": [
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1049882",
        "https://bugzilla-attachments.redhat.com/attachment.cgi?id=1049883"
    ],
    "comment": [
        "The following flaw was found in Django:\n\n'django.core.validators.URLValidator' included a regular expression that was extremely slow to evaluate against certain invalid inputs. This regular expression has been simplified and optimized.\n\nThis flaw has been fixed in Django version 1.8.3.\n\nAcknowledgements:\n\nRed Hat would like to thank the upstream Django project for reporting this issue.",
        "Createdattachment 1049118[details]urlvalidator-1.8.x.diff",
        "Createdattachment 1049119[details]urlvalidator-master.diff",
        "Createdattachment 1049882[details]urlvalidator-1.8.x.diff",
        "Createdattachment 1049883[details]urlvalidator-master.diff",
        "This is now public:https://www.djangoproject.com/weblog/2015/jul/08/security-releases/",
        "python-django-1.8.3-1.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
    ]
}